SAMPLE_BERITA = [
    ('Kemenkes Ingatkan Bahaya Diabetes bagi Generasi Muda', 'https://health.detik.com/diabetes/d-7600001/kemenkes-ingatkan-bahaya-diabetes-bagi-generasi-muda'),
    ('Waspadai Gejala Stres Menurut Pakar Kesehatan', 'https://health.detik.com/mental/d-7600002/waspadai-gejala-stres-menurut-pakar-kesehatan'),
    ('Penelitian Baru Kaitkan Perubahan iklim bagi Kesehatan Tubuh', 'https://health.detik.com/lingkungan/d-7600003/penelitian-baru-kaitkan-perubahan-iklim-bagi-kesehatan-tubuh'),
    ('Ahli Sarankan Cara Atasi Gula darah bagi Kesehatan Tubuh', 'https://health.detik.com/diabetes/d-7600004/ahli-sarankan-cara-atasi-gula-darah-bagi-kesehatan-tubuh'),
    ('Kabar Baik: Cara Baru Atasi Osteoporosis Setiap Hari', 'https://health.detik.com/lansia/d-7600005/kabar-baik-cara-baru-atasi-osteoporosis-setiap-hari'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Burnout di Tengah Cuaca Ekstrem', 'https://health.detik.com/mental/d-7600006/hatihati-ini-risiko-tersembunyi-dari-burnout-di-tengah-cuaca'),
    ('Ini Cara Mudah Cegah Serangan jantung untuk Jangka Panjang', 'https://health.detik.com/jantung/d-7600007/ini-cara-mudah-cegah-serangan-jantung-untuk-jangka-panjang'),
    ('Tips Sederhana Mencegah Jalan kaki untuk Jangka Panjang', 'https://health.detik.com/olahraga/d-7600008/tips-sederhana-mencegah-jalan-kaki-untuk-jangka-panjang'),
    ('Pakar Ungkap Fakta Seputar Diabetes di Musim Ini', 'https://health.detik.com/diabetes/d-7600009/pakar-ungkap-fakta-seputar-diabetes-di-musim-ini'),
    ('Fakta Medis di Balik Serat makanan di Tengah Cuaca Ekstrem', 'https://health.detik.com/makanan/d-7600010/fakta-medis-di-balik-serat-makanan-di-tengah-cuaca-ekstrem'),
    ('Kabar Baik: Cara Baru Atasi Tekanan darah tinggi di Musim Ini', 'https://health.detik.com/jantung/d-7600011/kabar-baik-cara-baru-atasi-tekanan-darah-tinggi-di-musim-ini'),
    ('Kabar Baik: Cara Baru Atasi Flu musiman Kata Dokter Spesialis', 'https://health.detik.com/infeksi/d-7600012/kabar-baik-cara-baru-atasi-flu-musiman-kata-dokter-spesialis'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Dehidrasi Menurut Penelitian Terbaru', 'https://health.detik.com/lingkungan/d-7600013/hatihati-ini-risiko-tersembunyi-dari-dehidrasi-menurut-penel'),
    ('Ahli Sarankan Cara Atasi Diabetes Kata Dokter Spesialis', 'https://health.detik.com/diabetes/d-7600014/ahli-sarankan-cara-atasi-diabetes-kata-dokter-spesialis'),
    ('Waspadai Gejala Gula darah Agar Tetap Bugar', 'https://health.detik.com/diabetes/d-7600015/waspadai-gejala-gula-darah-agar-tetap-bugar'),
    ('Riset Terbaru Tunjukkan Dampak Lari pagi Sebelum Terlambat', 'https://health.detik.com/olahraga/d-7600016/riset-terbaru-tunjukkan-dampak-lari-pagi-sebelum-terlambat'),
    ('Tips Sederhana Mencegah Serat makanan di Tengah Cuaca Ekstrem', 'https://health.detik.com/makanan/d-7600017/tips-sederhana-mencegah-serat-makanan-di-tengah-cuaca-ekstre'),
    ('Pentingnya Menjaga Resistensi insulin bagi Generasi Muda', 'https://health.detik.com/diabetes/d-7600018/pentingnya-menjaga-resistensi-insulin-bagi-generasi-muda'),
    ('Pakar Ungkap Fakta Seputar Gadget pada anak di Tengah Cuaca Ekstrem', 'https://health.detik.com/anak/d-7600019/pakar-ungkap-fakta-seputar-gadget-pada-anak-di-tengah-cuaca-'),
    ('IDAI Imbau Orang Tua Waspada Osteoporosis yang Perlu Diketahui', 'https://health.detik.com/lansia/d-7600020/idai-imbau-orang-tua-waspada-osteoporosis-yang-perlu-diketah'),
    ('IDAI Imbau Orang Tua Waspada Kesehatan mental Agar Tetap Bugar', 'https://health.detik.com/mental/d-7600021/idai-imbau-orang-tua-waspada-kesehatan-mental-agar-tetap-bug'),
    ('Tips Sederhana Mencegah Olahraga rutin untuk Jangka Panjang', 'https://health.detik.com/olahraga/d-7600022/tips-sederhana-mencegah-olahraga-rutin-untuk-jangka-panjang'),
    ('Pakar Ungkap Fakta Seputar Burnout di Era Modern', 'https://health.detik.com/mental/d-7600023/pakar-ungkap-fakta-seputar-burnout-di-era-modern'),
    ('Kenali Tanda-tanda Gizi anak bagi Generasi Muda', 'https://health.detik.com/anak/d-7600024/kenali-tandatanda-gizi-anak-bagi-generasi-muda'),
    ('Kemenkes Ingatkan Bahaya Daya ingat Setiap Hari', 'https://health.detik.com/lansia/d-7600025/kemenkes-ingatkan-bahaya-daya-ingat-setiap-hari'),
    ('Riset Terbaru Tunjukkan Dampak Perubahan iklim bagi Generasi Muda', 'https://health.detik.com/lingkungan/d-7600026/riset-terbaru-tunjukkan-dampak-perubahan-iklim-bagi-generasi'),
    ('Dampak Buruk Kebiasaan Terkait Stunting Menurut Pakar Kesehatan', 'https://health.detik.com/anak/d-7600027/dampak-buruk-kebiasaan-terkait-stunting-menurut-pakar-keseha'),
    ('Kenali Tanda-tanda Penyakit jantung Sebelum Terlambat', 'https://health.detik.com/jantung/d-7600028/kenali-tandatanda-penyakit-jantung-sebelum-terlambat'),
    ('Dokter Jelaskan Hepatitis Agar Tetap Bugar', 'https://health.detik.com/infeksi/d-7600029/dokter-jelaskan-hepatitis-agar-tetap-bugar'),
    ('Manfaat Tak Terduga dari Hepatitis di Tengah Cuaca Ekstrem', 'https://health.detik.com/infeksi/d-7600030/manfaat-tak-terduga-dari-hepatitis-di-tengah-cuaca-ekstrem'),
    ('Waspadai Gejala Kesehatan lansia di Tengah Cuaca Ekstrem', 'https://health.detik.com/lansia/d-7600031/waspadai-gejala-kesehatan-lansia-di-tengah-cuaca-ekstrem'),
    ('BPOM Rilis Peringatan Soal Pola makan sehat Setiap Hari', 'https://health.detik.com/makanan/d-7600032/bpom-rilis-peringatan-soal-pola-makan-sehat-setiap-hari'),
    ('Studi Terbaru Ungkap Gadget pada anak di Tengah Cuaca Ekstrem', 'https://health.detik.com/anak/d-7600033/studi-terbaru-ungkap-gadget-pada-anak-di-tengah-cuaca-ekstre'),
    ('Jangan Abaikan Gejala Osteoporosis di Musim Ini', 'https://health.detik.com/lansia/d-7600034/jangan-abaikan-gejala-osteoporosis-di-musim-ini'),
    ('Fakta Medis di Balik Latihan beban Menurut Penelitian Terbaru', 'https://health.detik.com/olahraga/d-7600035/fakta-medis-di-balik-latihan-beban-menurut-penelitian-terbar'),
    ('Pentingnya Menjaga Gizi anak bagi Kesehatan Tubuh', 'https://health.detik.com/anak/d-7600036/pentingnya-menjaga-gizi-anak-bagi-kesehatan-tubuh'),
    ('Dampak Buruk Kebiasaan Terkait Dehidrasi bagi Kesehatan Tubuh', 'https://health.detik.com/lingkungan/d-7600037/dampak-buruk-kebiasaan-terkait-dehidrasi-bagi-kesehatan-tubu'),
    ('BPOM Rilis Peringatan Soal Insulin bagi Generasi Muda', 'https://health.detik.com/diabetes/d-7600038/bpom-rilis-peringatan-soal-insulin-bagi-generasi-muda'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Serangan jantung Menurut Pakar Kesehatan', 'https://health.detik.com/jantung/d-7600039/hatihati-ini-risiko-tersembunyi-dari-serangan-jantung-menuru'),
    ('Dokter Jelaskan Obesitas pada Anak dan Dewasa', 'https://health.detik.com/diabetes/d-7600040/dokter-jelaskan-obesitas-pada-anak-dan-dewasa'),
    ('Kabar Baik: Cara Baru Atasi Gadget pada anak Sebelum Terlambat', 'https://health.detik.com/anak/d-7600041/kabar-baik-cara-baru-atasi-gadget-pada-anak-sebelum-terlamba'),
    ('Fakta Medis di Balik Latihan beban Setiap Hari', 'https://health.detik.com/olahraga/d-7600042/fakta-medis-di-balik-latihan-beban-setiap-hari'),
    ('Tips Sederhana Mencegah Depresi Kata Dokter Spesialis', 'https://health.detik.com/mental/d-7600043/tips-sederhana-mencegah-depresi-kata-dokter-spesialis'),
    ('Manfaat Tak Terduga dari Cacar monyet di Era Modern', 'https://health.detik.com/infeksi/d-7600044/manfaat-tak-terduga-dari-cacar-monyet-di-era-modern'),
    ('Ahli Sarankan Cara Atasi Gula darah Menurut Pakar Kesehatan', 'https://health.detik.com/diabetes/d-7600045/ahli-sarankan-cara-atasi-gula-darah-menurut-pakar-kesehatan'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Pola makan sehat bagi Generasi Muda', 'https://health.detik.com/makanan/d-7600046/hatihati-ini-risiko-tersembunyi-dari-pola-makan-sehat-bagi-g'),
    ('Studi Terbaru Ungkap Cuaca panas ekstrem Menurut Pakar Kesehatan', 'https://health.detik.com/lingkungan/d-7600047/studi-terbaru-ungkap-cuaca-panas-ekstrem-menurut-pakar-keseh'),
    ('Dokter Jelaskan Serangan jantung yang Perlu Diketahui', 'https://health.detik.com/jantung/d-7600048/dokter-jelaskan-serangan-jantung-yang-perlu-diketahui'),
    ('Jangan Abaikan Gejala Pola makan sehat bagi Generasi Muda', 'https://health.detik.com/makanan/d-7600049/jangan-abaikan-gejala-pola-makan-sehat-bagi-generasi-muda'),
    ('Tips Sederhana Mencegah Lari pagi pada Anak dan Dewasa', 'https://health.detik.com/olahraga/d-7600050/tips-sederhana-mencegah-lari-pagi-pada-anak-dan-dewasa'),
    ('Dampak Buruk Kebiasaan Terkait Kualitas udara bagi Generasi Muda', 'https://health.detik.com/lingkungan/d-7600051/dampak-buruk-kebiasaan-terkait-kualitas-udara-bagi-generasi-'),
    ('Tips Sederhana Mencegah Pola tidur di Musim Ini', 'https://health.detik.com/tidur/d-7600052/tips-sederhana-mencegah-pola-tidur-di-musim-ini'),
    ('Riset Terbaru Tunjukkan Dampak Obesitas Setiap Hari', 'https://health.detik.com/diabetes/d-7600053/riset-terbaru-tunjukkan-dampak-obesitas-setiap-hari'),
    ('Penelitian Baru Kaitkan Tbc di Musim Ini', 'https://health.detik.com/infeksi/d-7600054/penelitian-baru-kaitkan-tbc-di-musim-ini'),
    ('IDAI Imbau Orang Tua Waspada Tekanan darah tinggi di Musim Ini', 'https://health.detik.com/jantung/d-7600055/idai-imbau-orang-tua-waspada-tekanan-darah-tinggi-di-musim-i'),
    ('Tips Sederhana Mencegah Stres di Era Modern', 'https://health.detik.com/mental/d-7600056/tips-sederhana-mencegah-stres-di-era-modern'),
    ('Pentingnya Menjaga Gadget pada anak di Tengah Cuaca Ekstrem', 'https://health.detik.com/anak/d-7600057/pentingnya-menjaga-gadget-pada-anak-di-tengah-cuaca-ekstrem'),
    ('Dokter Jelaskan Kurang tidur di Era Modern', 'https://health.detik.com/tidur/d-7600058/dokter-jelaskan-kurang-tidur-di-era-modern'),
    ('Penelitian Baru Kaitkan Kesehatan lansia bagi Kesehatan Tubuh', 'https://health.detik.com/lansia/d-7600059/penelitian-baru-kaitkan-kesehatan-lansia-bagi-kesehatan-tubu'),
    ('Pentingnya Menjaga Gula darah Setiap Hari', 'https://health.detik.com/diabetes/d-7600060/pentingnya-menjaga-gula-darah-setiap-hari'),
    ('Tips Sederhana Mencegah Pola tidur Agar Tetap Bugar', 'https://health.detik.com/tidur/d-7600061/tips-sederhana-mencegah-pola-tidur-agar-tetap-bugar'),
    ('Pakar Ungkap Fakta Seputar Serangan jantung bagi Kesehatan Tubuh', 'https://health.detik.com/jantung/d-7600062/pakar-ungkap-fakta-seputar-serangan-jantung-bagi-kesehatan-t'),
    ('Manfaat Tak Terduga dari Cacar monyet Kata Dokter Spesialis', 'https://health.detik.com/infeksi/d-7600063/manfaat-tak-terduga-dari-cacar-monyet-kata-dokter-spesialis'),
    ('Dampak Buruk Kebiasaan Terkait Hepatitis pada Anak dan Dewasa', 'https://health.detik.com/infeksi/d-7600064/dampak-buruk-kebiasaan-terkait-hepatitis-pada-anak-dan-dewas'),
    ('Tips Sederhana Mencegah Kecemasan yang Perlu Diketahui', 'https://health.detik.com/mental/d-7600065/tips-sederhana-mencegah-kecemasan-yang-perlu-diketahui'),
    ('Penelitian Baru Kaitkan Kualitas udara untuk Jangka Panjang', 'https://health.detik.com/lingkungan/d-7600066/penelitian-baru-kaitkan-kualitas-udara-untuk-jangka-panjang'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Penyakit jantung', 'https://health.detik.com/jantung/d-7600067/hatihati-ini-risiko-tersembunyi-dari-penyakit-jantung'),
    ('Pentingnya Menjaga Daya ingat yang Perlu Diketahui', 'https://health.detik.com/lansia/d-7600068/pentingnya-menjaga-daya-ingat-yang-perlu-diketahui'),
    ('Pentingnya Menjaga Kesehatan lansia Menurut Pakar Kesehatan', 'https://health.detik.com/lansia/d-7600069/pentingnya-menjaga-kesehatan-lansia-menurut-pakar-kesehatan'),
    ('Ahli Sarankan Cara Atasi Polusi udara Agar Tetap Bugar', 'https://health.detik.com/lingkungan/d-7600070/ahli-sarankan-cara-atasi-polusi-udara-agar-tetap-bugar'),
    ('Ahli Sarankan Cara Atasi Resistensi insulin yang Perlu Diketahui', 'https://health.detik.com/diabetes/d-7600071/ahli-sarankan-cara-atasi-resistensi-insulin-yang-perlu-diket'),
    ('Ini Cara Mudah Cegah Polusi udara untuk Jangka Panjang', 'https://health.detik.com/lingkungan/d-7600072/ini-cara-mudah-cegah-polusi-udara-untuk-jangka-panjang'),
    ('IDAI Imbau Orang Tua Waspada Jalan kaki bagi Generasi Muda', 'https://health.detik.com/olahraga/d-7600073/idai-imbau-orang-tua-waspada-jalan-kaki-bagi-generasi-muda'),
    ('Kenali Tanda-tanda Lari pagi Kata Dokter Spesialis', 'https://health.detik.com/olahraga/d-7600074/kenali-tandatanda-lari-pagi-kata-dokter-spesialis'),
    ('Dokter Jelaskan Insomnia bagi Kesehatan Tubuh', 'https://health.detik.com/tidur/d-7600075/dokter-jelaskan-insomnia-bagi-kesehatan-tubuh'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Gangguan tidur di Musim Ini', 'https://health.detik.com/tidur/d-7600076/hatihati-ini-risiko-tersembunyi-dari-gangguan-tidur-di-musim'),
    ('Tips Sederhana Mencegah Resistensi insulin di Tengah Cuaca Ekstrem', 'https://health.detik.com/diabetes/d-7600077/tips-sederhana-mencegah-resistensi-insulin-di-tengah-cuaca-e'),
    ('Dokter Jelaskan Gizi anak bagi Generasi Muda', 'https://health.detik.com/anak/d-7600078/dokter-jelaskan-gizi-anak-bagi-generasi-muda'),
    ('Pentingnya Menjaga Serat makanan di Era Modern', 'https://health.detik.com/makanan/d-7600079/pentingnya-menjaga-serat-makanan-di-era-modern'),
    ('Fakta Medis di Balik Demensia bagi Kesehatan Tubuh', 'https://health.detik.com/lansia/d-7600080/fakta-medis-di-balik-demensia-bagi-kesehatan-tubuh'),
    ('Waspadai Gejala Demensia pada Anak dan Dewasa', 'https://health.detik.com/lansia/d-7600081/waspadai-gejala-demensia-pada-anak-dan-dewasa'),
    ('Waspadai Gejala Olahraga rutin pada Anak dan Dewasa', 'https://health.detik.com/olahraga/d-7600082/waspadai-gejala-olahraga-rutin-pada-anak-dan-dewasa'),
    ('Fakta Medis di Balik Yoga Menurut Penelitian Terbaru', 'https://health.detik.com/olahraga/d-7600083/fakta-medis-di-balik-yoga-menurut-penelitian-terbaru'),
    ('Kemenkes Ingatkan Bahaya Konsumsi gula', 'https://health.detik.com/makanan/d-7600084/kemenkes-ingatkan-bahaya-konsumsi-gula'),
    ('Dokter Jelaskan Olahraga rutin Setiap Hari', 'https://health.detik.com/olahraga/d-7600085/dokter-jelaskan-olahraga-rutin-setiap-hari'),
    ('Studi Terbaru Ungkap Olahraga rutin untuk Jangka Panjang', 'https://health.detik.com/olahraga/d-7600086/studi-terbaru-ungkap-olahraga-rutin-untuk-jangka-panjang'),
    ('Pentingnya Menjaga Gizi anak di Era Modern', 'https://health.detik.com/anak/d-7600087/pentingnya-menjaga-gizi-anak-di-era-modern'),
    ('Kabar Baik: Cara Baru Atasi Radang sendi bagi Kesehatan Tubuh', 'https://health.detik.com/lansia/d-7600088/kabar-baik-cara-baru-atasi-radang-sendi-bagi-kesehatan-tubuh'),
    ('Kenali Tanda-tanda Diabetes yang Perlu Diketahui', 'https://health.detik.com/diabetes/d-7600089/kenali-tandatanda-diabetes-yang-perlu-diketahui'),
    ('Kabar Baik: Cara Baru Atasi Diet seimbang pada Anak dan Dewasa', 'https://health.detik.com/makanan/d-7600090/kabar-baik-cara-baru-atasi-diet-seimbang-pada-anak-dan-dewas'),
    ('Penelitian Baru Kaitkan Dbd Kata Dokter Spesialis', 'https://health.detik.com/infeksi/d-7600091/penelitian-baru-kaitkan-dbd-kata-dokter-spesialis'),
    ('Riset Terbaru Tunjukkan Dampak Pola makan sehat Menurut Penelitian Terbaru', 'https://health.detik.com/makanan/d-7600092/riset-terbaru-tunjukkan-dampak-pola-makan-sehat-menurut-pene'),
    ('Riset Terbaru Tunjukkan Dampak Kesehatan mental Setiap Hari', 'https://health.detik.com/mental/d-7600093/riset-terbaru-tunjukkan-dampak-kesehatan-mental-setiap-hari'),
    ('Ahli Sarankan Cara Atasi Cuaca panas ekstrem Sebelum Terlambat', 'https://health.detik.com/lingkungan/d-7600094/ahli-sarankan-cara-atasi-cuaca-panas-ekstrem-sebelum-terlamb'),
    ('Studi Terbaru Ungkap Gadget pada anak Sebelum Terlambat', 'https://health.detik.com/anak/d-7600095/studi-terbaru-ungkap-gadget-pada-anak-sebelum-terlambat'),
    ('Ahli Sarankan Cara Atasi Makanan olahan di Tengah Cuaca Ekstrem', 'https://health.detik.com/makanan/d-7600096/ahli-sarankan-cara-atasi-makanan-olahan-di-tengah-cuaca-ekst'),
    ('Pakar Ungkap Fakta Seputar Tumbuh kembang anak yang Perlu Diketahui', 'https://health.detik.com/anak/d-7600097/pakar-ungkap-fakta-seputar-tumbuh-kembang-anak-yang-perlu-di'),
    ('Tips Sederhana Mencegah Kurang tidur di Era Modern', 'https://health.detik.com/tidur/d-7600098/tips-sederhana-mencegah-kurang-tidur-di-era-modern'),
    ('Ahli Sarankan Cara Atasi Serat makanan bagi Generasi Muda', 'https://health.detik.com/makanan/d-7600099/ahli-sarankan-cara-atasi-serat-makanan-bagi-generasi-muda'),
    ('Pakar Ungkap Fakta Seputar Serangan jantung untuk Jangka Panjang', 'https://health.detik.com/jantung/d-7600100/pakar-ungkap-fakta-seputar-serangan-jantung-untuk-jangka-pan'),
    ('Kemenkes Ingatkan Bahaya Olahraga rutin Sejak Dini', 'https://health.detik.com/olahraga/d-7600101/kemenkes-ingatkan-bahaya-olahraga-rutin-sejak-dini'),
    ('Kabar Baik: Cara Baru Atasi Radang sendi untuk Jangka Panjang', 'https://health.detik.com/lansia/d-7600102/kabar-baik-cara-baru-atasi-radang-sendi-untuk-jangka-panjang'),
    ('Kemenkes Ingatkan Bahaya Penyakit jantung Sebelum Terlambat', 'https://health.detik.com/jantung/d-7600103/kemenkes-ingatkan-bahaya-penyakit-jantung-sebelum-terlambat'),
    ('Penelitian Baru Kaitkan Dehidrasi di Musim Ini', 'https://health.detik.com/lingkungan/d-7600104/penelitian-baru-kaitkan-dehidrasi-di-musim-ini'),
    ('Riset Terbaru Tunjukkan Dampak Perubahan iklim untuk Jangka Panjang', 'https://health.detik.com/lingkungan/d-7600105/riset-terbaru-tunjukkan-dampak-perubahan-iklim-untuk-jangka-'),
    ('Jangan Abaikan Gejala Hepatitis di Musim Ini', 'https://health.detik.com/infeksi/d-7600106/jangan-abaikan-gejala-hepatitis-di-musim-ini'),
    ('Tips Sederhana Mencegah Hepatitis di Tengah Cuaca Ekstrem', 'https://health.detik.com/infeksi/d-7600107/tips-sederhana-mencegah-hepatitis-di-tengah-cuaca-ekstrem'),
    ('Studi Terbaru Ungkap Tekanan darah tinggi Menurut Penelitian Terbaru', 'https://health.detik.com/jantung/d-7600108/studi-terbaru-ungkap-tekanan-darah-tinggi-menurut-penelitian'),
    ('Dokter Jelaskan Makanan olahan untuk Jangka Panjang', 'https://health.detik.com/makanan/d-7600109/dokter-jelaskan-makanan-olahan-untuk-jangka-panjang'),
    ('Waspadai Gejala Dehidrasi Kata Dokter Spesialis', 'https://health.detik.com/lingkungan/d-7600110/waspadai-gejala-dehidrasi-kata-dokter-spesialis'),
    ('Ini Cara Mudah Cegah Demensia untuk Jangka Panjang', 'https://health.detik.com/lansia/d-7600111/ini-cara-mudah-cegah-demensia-untuk-jangka-panjang'),
    ('Kabar Baik: Cara Baru Atasi Cacar monyet pada Anak dan Dewasa', 'https://health.detik.com/infeksi/d-7600112/kabar-baik-cara-baru-atasi-cacar-monyet-pada-anak-dan-dewasa'),
    ('Pakar Ungkap Fakta Seputar Burnout Sebelum Terlambat', 'https://health.detik.com/mental/d-7600113/pakar-ungkap-fakta-seputar-burnout-sebelum-terlambat'),
    ('BPOM Rilis Peringatan Soal Kualitas udara Agar Tetap Bugar', 'https://health.detik.com/lingkungan/d-7600114/bpom-rilis-peringatan-soal-kualitas-udara-agar-tetap-bugar'),
    ('BPOM Rilis Peringatan Soal Kesehatan lansia Kata Dokter Spesialis', 'https://health.detik.com/lansia/d-7600115/bpom-rilis-peringatan-soal-kesehatan-lansia-kata-dokter-spes'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Burnout untuk Jangka Panjang', 'https://health.detik.com/mental/d-7600116/hatihati-ini-risiko-tersembunyi-dari-burnout-untuk-jangka-pa'),
    ('Manfaat Tak Terduga dari Pola tidur Menurut Penelitian Terbaru', 'https://health.detik.com/tidur/d-7600117/manfaat-tak-terduga-dari-pola-tidur-menurut-penelitian-terba'),
    ('Pentingnya Menjaga Radang sendi Menurut Pakar Kesehatan', 'https://health.detik.com/lansia/d-7600118/pentingnya-menjaga-radang-sendi-menurut-pakar-kesehatan'),
    ('Fakta Medis di Balik Latihan beban untuk Jangka Panjang', 'https://health.detik.com/olahraga/d-7600119/fakta-medis-di-balik-latihan-beban-untuk-jangka-panjang'),
    ('BPOM Rilis Peringatan Soal Gula darah bagi Generasi Muda', 'https://health.detik.com/diabetes/d-7600120/bpom-rilis-peringatan-soal-gula-darah-bagi-generasi-muda'),
    ('Studi Terbaru Ungkap Stres yang Perlu Diketahui', 'https://health.detik.com/mental/d-7600121/studi-terbaru-ungkap-stres-yang-perlu-diketahui'),
    ('Fakta Medis di Balik Burnout Menurut Pakar Kesehatan', 'https://health.detik.com/mental/d-7600122/fakta-medis-di-balik-burnout-menurut-pakar-kesehatan'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Pola tidur Menurut Penelitian Terbaru', 'https://health.detik.com/tidur/d-7600123/hatihati-ini-risiko-tersembunyi-dari-pola-tidur-menurut-pene'),
    ('Pakar Ungkap Fakta Seputar Tbc bagi Generasi Muda', 'https://health.detik.com/infeksi/d-7600124/pakar-ungkap-fakta-seputar-tbc-bagi-generasi-muda'),
    ('Waspadai Gejala Tumbuh kembang anak Setiap Hari', 'https://health.detik.com/anak/d-7600125/waspadai-gejala-tumbuh-kembang-anak-setiap-hari'),
    ('Jangan Abaikan Gejala Stres di Era Modern', 'https://health.detik.com/mental/d-7600126/jangan-abaikan-gejala-stres-di-era-modern'),
    ('Ahli Sarankan Cara Atasi Jantung bawaan di Musim Ini', 'https://health.detik.com/jantung/d-7600127/ahli-sarankan-cara-atasi-jantung-bawaan-di-musim-ini'),
    ('Manfaat Tak Terduga dari Kurang tidur untuk Jangka Panjang', 'https://health.detik.com/tidur/d-7600128/manfaat-tak-terduga-dari-kurang-tidur-untuk-jangka-panjang'),
    ('Jangan Abaikan Gejala Gangguan tidur Setiap Hari', 'https://health.detik.com/tidur/d-7600129/jangan-abaikan-gejala-gangguan-tidur-setiap-hari'),
    ('Pentingnya Menjaga Radang sendi', 'https://health.detik.com/lansia/d-7600130/pentingnya-menjaga-radang-sendi'),
    ('Ahli Sarankan Cara Atasi Insomnia di Tengah Cuaca Ekstrem', 'https://health.detik.com/tidur/d-7600131/ahli-sarankan-cara-atasi-insomnia-di-tengah-cuaca-ekstrem'),
    ('Ahli Sarankan Cara Atasi Radang sendi di Tengah Cuaca Ekstrem', 'https://health.detik.com/lansia/d-7600132/ahli-sarankan-cara-atasi-radang-sendi-di-tengah-cuaca-ekstre'),
    ('BPOM Rilis Peringatan Soal Kualitas tidur bagi Generasi Muda', 'https://health.detik.com/tidur/d-7600133/bpom-rilis-peringatan-soal-kualitas-tidur-bagi-generasi-muda'),
    ('IDAI Imbau Orang Tua Waspada Yoga Menurut Pakar Kesehatan', 'https://health.detik.com/olahraga/d-7600134/idai-imbau-orang-tua-waspada-yoga-menurut-pakar-kesehatan'),
    ('Ahli Sarankan Cara Atasi Imunisasi anak Agar Tetap Bugar', 'https://health.detik.com/anak/d-7600135/ahli-sarankan-cara-atasi-imunisasi-anak-agar-tetap-bugar'),
    ('Dokter Jelaskan Imunisasi anak Setiap Hari', 'https://health.detik.com/anak/d-7600136/dokter-jelaskan-imunisasi-anak-setiap-hari'),
    ('Kabar Baik: Cara Baru Atasi Cacar monyet di Era Modern', 'https://health.detik.com/infeksi/d-7600137/kabar-baik-cara-baru-atasi-cacar-monyet-di-era-modern'),
    ('Tips Sederhana Mencegah Flu musiman Setiap Hari', 'https://health.detik.com/infeksi/d-7600138/tips-sederhana-mencegah-flu-musiman-setiap-hari'),
    ('Studi Terbaru Ungkap Hepatitis Agar Tetap Bugar', 'https://health.detik.com/infeksi/d-7600139/studi-terbaru-ungkap-hepatitis-agar-tetap-bugar'),
    ('Riset Terbaru Tunjukkan Dampak Kualitas tidur Kata Dokter Spesialis', 'https://health.detik.com/tidur/d-7600140/riset-terbaru-tunjukkan-dampak-kualitas-tidur-kata-dokter-sp'),
    ('Kabar Baik: Cara Baru Atasi Tbc bagi Generasi Muda', 'https://health.detik.com/infeksi/d-7600141/kabar-baik-cara-baru-atasi-tbc-bagi-generasi-muda'),
    ('Kemenkes Ingatkan Bahaya Kurang tidur Setiap Hari', 'https://health.detik.com/tidur/d-7600142/kemenkes-ingatkan-bahaya-kurang-tidur-setiap-hari'),
    ('Pakar Ungkap Fakta Seputar Kualitas tidur untuk Jangka Panjang', 'https://health.detik.com/tidur/d-7600143/pakar-ungkap-fakta-seputar-kualitas-tidur-untuk-jangka-panja'),
    ('Manfaat Tak Terduga dari Dbd pada Anak dan Dewasa', 'https://health.detik.com/infeksi/d-7600144/manfaat-tak-terduga-dari-dbd-pada-anak-dan-dewasa'),
    ('Studi Terbaru Ungkap Kualitas udara Agar Tetap Bugar', 'https://health.detik.com/lingkungan/d-7600145/studi-terbaru-ungkap-kualitas-udara-agar-tetap-bugar'),
    ('Studi Terbaru Ungkap Kualitas udara Menurut Pakar Kesehatan', 'https://health.detik.com/lingkungan/d-7600146/studi-terbaru-ungkap-kualitas-udara-menurut-pakar-kesehatan'),
    ('Manfaat Tak Terduga dari Dbd Sebelum Terlambat', 'https://health.detik.com/infeksi/d-7600147/manfaat-tak-terduga-dari-dbd-sebelum-terlambat'),
    ('Pakar Ungkap Fakta Seputar Kolesterol untuk Jangka Panjang', 'https://health.detik.com/jantung/d-7600148/pakar-ungkap-fakta-seputar-kolesterol-untuk-jangka-panjang'),
    ('IDAI Imbau Orang Tua Waspada Burnout untuk Jangka Panjang', 'https://health.detik.com/mental/d-7600149/idai-imbau-orang-tua-waspada-burnout-untuk-jangka-panjang'),
    ('Ini Cara Mudah Cegah Cacar monyet di Tengah Cuaca Ekstrem', 'https://health.detik.com/infeksi/d-7600150/ini-cara-mudah-cegah-cacar-monyet-di-tengah-cuaca-ekstrem'),
    ('Studi Terbaru Ungkap Obesitas yang Perlu Diketahui', 'https://health.detik.com/diabetes/d-7600151/studi-terbaru-ungkap-obesitas-yang-perlu-diketahui'),
    ('Dokter Jelaskan Konsumsi gula yang Perlu Diketahui', 'https://health.detik.com/makanan/d-7600152/dokter-jelaskan-konsumsi-gula-yang-perlu-diketahui'),
    ('Tips Sederhana Mencegah Serangan jantung bagi Kesehatan Tubuh', 'https://health.detik.com/jantung/d-7600153/tips-sederhana-mencegah-serangan-jantung-bagi-kesehatan-tubu'),
    ('Ahli Sarankan Cara Atasi Cuaca panas ekstrem pada Anak dan Dewasa', 'https://health.detik.com/lingkungan/d-7600154/ahli-sarankan-cara-atasi-cuaca-panas-ekstrem-pada-anak-dan-d'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Kualitas tidur Menurut Penelitian Terbaru', 'https://health.detik.com/tidur/d-7600155/hatihati-ini-risiko-tersembunyi-dari-kualitas-tidur-menurut-'),
    ('Riset Terbaru Tunjukkan Dampak Insomnia Sebelum Terlambat', 'https://health.detik.com/tidur/d-7600156/riset-terbaru-tunjukkan-dampak-insomnia-sebelum-terlambat'),
    ('Waspadai Gejala Kualitas udara Sebelum Terlambat', 'https://health.detik.com/lingkungan/d-7600157/waspadai-gejala-kualitas-udara-sebelum-terlambat'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Olahraga rutin bagi Kesehatan Tubuh', 'https://health.detik.com/olahraga/d-7600158/hatihati-ini-risiko-tersembunyi-dari-olahraga-rutin-bagi-kes'),
    ('Pakar Ungkap Fakta Seputar Latihan beban Agar Tetap Bugar', 'https://health.detik.com/olahraga/d-7600159/pakar-ungkap-fakta-seputar-latihan-beban-agar-tetap-bugar'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Kesehatan mental bagi Generasi Muda', 'https://health.detik.com/mental/d-7600160/hatihati-ini-risiko-tersembunyi-dari-kesehatan-mental-bagi-g'),
    ('Fakta Medis di Balik Insulin di Musim Ini', 'https://health.detik.com/diabetes/d-7600161/fakta-medis-di-balik-insulin-di-musim-ini'),
    ('Riset Terbaru Tunjukkan Dampak Polusi udara Setiap Hari', 'https://health.detik.com/lingkungan/d-7600162/riset-terbaru-tunjukkan-dampak-polusi-udara-setiap-hari'),
    ('Jangan Abaikan Gejala Pola makan sehat untuk Jangka Panjang', 'https://health.detik.com/makanan/d-7600163/jangan-abaikan-gejala-pola-makan-sehat-untuk-jangka-panjang'),
    ('Dampak Buruk Kebiasaan Terkait Tekanan darah tinggi di Musim Ini', 'https://health.detik.com/jantung/d-7600164/dampak-buruk-kebiasaan-terkait-tekanan-darah-tinggi-di-musim'),
    ('Manfaat Tak Terduga dari Cacar monyet pada Anak dan Dewasa', 'https://health.detik.com/infeksi/d-7600165/manfaat-tak-terduga-dari-cacar-monyet-pada-anak-dan-dewasa'),
    ('Jangan Abaikan Gejala Dbd di Tengah Cuaca Ekstrem', 'https://health.detik.com/infeksi/d-7600166/jangan-abaikan-gejala-dbd-di-tengah-cuaca-ekstrem'),
    ('Dampak Buruk Kebiasaan Terkait Kualitas udara di Era Modern', 'https://health.detik.com/lingkungan/d-7600167/dampak-buruk-kebiasaan-terkait-kualitas-udara-di-era-modern'),
    ('Kemenkes Ingatkan Bahaya Hepatitis untuk Jangka Panjang', 'https://health.detik.com/infeksi/d-7600168/kemenkes-ingatkan-bahaya-hepatitis-untuk-jangka-panjang'),
    ('Kemenkes Ingatkan Bahaya Kesehatan mental di Era Modern', 'https://health.detik.com/mental/d-7600169/kemenkes-ingatkan-bahaya-kesehatan-mental-di-era-modern'),
    ('Hati-hati, Ini Risiko Tersembunyi dari Burnout Agar Tetap Bugar', 'https://health.detik.com/mental/d-7600170/hatihati-ini-risiko-tersembunyi-dari-burnout-agar-tetap-buga'),
    ('Dampak Buruk Kebiasaan Terkait Pola makan sehat untuk Jangka Panjang', 'https://health.detik.com/makanan/d-7600171/dampak-buruk-kebiasaan-terkait-pola-makan-sehat-untuk-jangka'),
    ('Tips Sederhana Mencegah Gadget pada anak Sejak Dini', 'https://health.detik.com/anak/d-7600172/tips-sederhana-mencegah-gadget-pada-anak-sejak-dini'),
    ('Kemenkes Ingatkan Bahaya Yoga di Tengah Cuaca Ekstrem', 'https://health.detik.com/olahraga/d-7600173/kemenkes-ingatkan-bahaya-yoga-di-tengah-cuaca-ekstrem'),
    ('Jangan Abaikan Gejala Kesehatan lansia Menurut Penelitian Terbaru', 'https://health.detik.com/lansia/d-7600174/jangan-abaikan-gejala-kesehatan-lansia-menurut-penelitian-te'),
    ('Ini Cara Mudah Cegah Gula darah', 'https://health.detik.com/diabetes/d-7600175/ini-cara-mudah-cegah-gula-darah'),
    ('Dampak Buruk Kebiasaan Terkait Osteoporosis', 'https://health.detik.com/lansia/d-7600176/dampak-buruk-kebiasaan-terkait-osteoporosis'),
    ('Dokter Jelaskan Kualitas tidur Kata Dokter Spesialis', 'https://health.detik.com/tidur/d-7600177/dokter-jelaskan-kualitas-tidur-kata-dokter-spesialis'),
    ('Ahli Sarankan Cara Atasi Burnout Kata Dokter Spesialis', 'https://health.detik.com/mental/d-7600178/ahli-sarankan-cara-atasi-burnout-kata-dokter-spesialis'),
    ('Dampak Buruk Kebiasaan Terkait Dehidrasi Sejak Dini', 'https://health.detik.com/lingkungan/d-7600179/dampak-buruk-kebiasaan-terkait-dehidrasi-sejak-dini'),
    ('IDAI Imbau Orang Tua Waspada Hepatitis Sejak Dini', 'https://health.detik.com/infeksi/d-7600180/idai-imbau-orang-tua-waspada-hepatitis-sejak-dini'),
    ('BPOM Rilis Peringatan Soal Insomnia di Tengah Cuaca Ekstrem', 'https://health.detik.com/tidur/d-7600181/bpom-rilis-peringatan-soal-insomnia-di-tengah-cuaca-ekstrem'),
    ('Tips Sederhana Mencegah Kesehatan mental untuk Jangka Panjang', 'https://health.detik.com/mental/d-7600182/tips-sederhana-mencegah-kesehatan-mental-untuk-jangka-panjan'),
    ('Pentingnya Menjaga Resistensi insulin Menurut Penelitian Terbaru', 'https://health.detik.com/diabetes/d-7600183/pentingnya-menjaga-resistensi-insulin-menurut-penelitian-ter'),
    ('Kemenkes Ingatkan Bahaya Burnout Kata Dokter Spesialis', 'https://health.detik.com/mental/d-7600184/kemenkes-ingatkan-bahaya-burnout-kata-dokter-spesialis'),
    ('BPOM Rilis Peringatan Soal Konsumsi gula bagi Kesehatan Tubuh', 'https://health.detik.com/makanan/d-7600185/bpom-rilis-peringatan-soal-konsumsi-gula-bagi-kesehatan-tubu'),
    ('Kemenkes Ingatkan Bahaya Osteoporosis yang Perlu Diketahui', 'https://health.detik.com/lansia/d-7600186/kemenkes-ingatkan-bahaya-osteoporosis-yang-perlu-diketahui'),
    ('BPOM Rilis Peringatan Soal Jantung bawaan pada Anak dan Dewasa', 'https://health.detik.com/jantung/d-7600187/bpom-rilis-peringatan-soal-jantung-bawaan-pada-anak-dan-dewa'),
    ('Studi Terbaru Ungkap Kualitas tidur Kata Dokter Spesialis', 'https://health.detik.com/tidur/d-7600188/studi-terbaru-ungkap-kualitas-tidur-kata-dokter-spesialis'),
    ('Manfaat Tak Terduga dari Pola tidur untuk Jangka Panjang', 'https://health.detik.com/tidur/d-7600189/manfaat-tak-terduga-dari-pola-tidur-untuk-jangka-panjang'),
    ('Kemenkes Ingatkan Bahaya Tumbuh kembang anak', 'https://health.detik.com/anak/d-7600190/kemenkes-ingatkan-bahaya-tumbuh-kembang-anak'),
    ('Pakar Ungkap Fakta Seputar Diabetes', 'https://health.detik.com/diabetes/d-7600191/pakar-ungkap-fakta-seputar-diabetes'),
    ('Penelitian Baru Kaitkan Resistensi insulin pada Anak dan Dewasa', 'https://health.detik.com/diabetes/d-7600192/penelitian-baru-kaitkan-resistensi-insulin-pada-anak-dan-dew'),
    ('BPOM Rilis Peringatan Soal Stunting Menurut Pakar Kesehatan', 'https://health.detik.com/anak/d-7600193/bpom-rilis-peringatan-soal-stunting-menurut-pakar-kesehatan'),
    ('Kabar Baik: Cara Baru Atasi Kesehatan mental Setiap Hari', 'https://health.detik.com/mental/d-7600194/kabar-baik-cara-baru-atasi-kesehatan-mental-setiap-hari'),
    ('Fakta Medis di Balik Kualitas udara bagi Generasi Muda', 'https://health.detik.com/lingkungan/d-7600195/fakta-medis-di-balik-kualitas-udara-bagi-generasi-muda'),
    ('Manfaat Tak Terduga dari Radang sendi di Era Modern', 'https://health.detik.com/lansia/d-7600196/manfaat-tak-terduga-dari-radang-sendi-di-era-modern'),
    ('Ini Cara Mudah Cegah Latihan beban Kata Dokter Spesialis', 'https://health.detik.com/olahraga/d-7600197/ini-cara-mudah-cegah-latihan-beban-kata-dokter-spesialis'),
    ('Penelitian Baru Kaitkan Kualitas udara di Musim Ini', 'https://health.detik.com/lingkungan/d-7600198/penelitian-baru-kaitkan-kualitas-udara-di-musim-ini'),
    ('Kemenkes Ingatkan Bahaya Stres Menurut Pakar Kesehatan', 'https://health.detik.com/mental/d-7600199/kemenkes-ingatkan-bahaya-stres-menurut-pakar-kesehatan'),
    ('Pentingnya Menjaga Imunisasi anak Menurut Pakar Kesehatan', 'https://health.detik.com/anak/d-7600200/pentingnya-menjaga-imunisasi-anak-menurut-pakar-kesehatan'),
]
