SAMPLE_BERITA = [
    ("Studi Terbaru Ungkap Manfaat Jalan Kaki 30 Menit Setiap Hari", "https://health.detik.com/berita-detikhealth/d-0001"),
    ("Kemenkes Ingatkan Warga Waspada Lonjakan Kasus DBD di Musim Hujan", "https://health.detik.com/berita-detikhealth/d-0002"),
    ("5 Kebiasaan Sederhana yang Bisa Menurunkan Risiko Diabetes", "https://health.detik.com/berita-detikhealth/d-0003"),
    ("Dokter Jelaskan Perbedaan Flu Biasa dan Flu Singapura pada Anak", "https://health.detik.com/berita-detikhealth/d-0004"),
    ("Riset: Kurang Tidur Bisa Tingkatkan Risiko Penyakit Jantung", "https://health.detik.com/berita-detikhealth/d-0005"),
    ("BPOM Rilis Daftar Obat Sirup yang Aman Dikonsumsi Anak", "https://health.detik.com/berita-detikhealth/d-0006"),
    ("Tips Menjaga Kesehatan Mental di Tengah Padatnya Pekerjaan", "https://health.detik.com/berita-detikhealth/d-0007"),
    ("Kasus Cacar Monyet Bertambah, Ini Gejala yang Perlu Diwaspadai", "https://health.detik.com/berita-detikhealth/d-0008"),
    ("Ahli Gizi Sarankan Konsumsi Serat untuk Jaga Kesehatan Usus", "https://health.detik.com/berita-detikhealth/d-0009"),
    ("Vaksinasi Booster Kedua Mulai Disarankan untuk Lansia", "https://health.detik.com/berita-detikhealth/d-0010"),
    ("Cara Sederhana Mengontrol Tekanan Darah Tinggi Tanpa Obat", "https://health.detik.com/berita-detikhealth/d-0011"),
    ("Penelitian Baru Kaitkan Polusi Udara dengan Gangguan Paru-paru", "https://health.detik.com/berita-detikhealth/d-0012"),
    ("Waspada Gejala Awal Stroke, Kenali Sebelum Terlambat", "https://health.detik.com/berita-detikhealth/d-0013"),
    ("Manfaat Olahraga Pagi bagi Kesehatan Jantung dan Paru", "https://health.detik.com/berita-detikhealth/d-0014"),
    ("IDAI Imbau Orang Tua Lengkapi Imunisasi Dasar Anak", "https://health.detik.com/berita-detikhealth/d-0015"),
    ("Kenali Gejala Asam Lambung Naik dan Cara Mengatasinya", "https://health.detik.com/berita-detikhealth/d-0016"),
    ("Studi: Konsumsi Gula Berlebih Tingkatkan Risiko Obesitas Anak", "https://health.detik.com/berita-detikhealth/d-0017"),
    ("Pentingnya Skrining Kesehatan Rutin untuk Deteksi Dini Kanker", "https://health.detik.com/berita-detikhealth/d-0018"),
    ("Dokter Bagikan Tips Menjaga Kualitas Tidur yang Baik", "https://health.detik.com/berita-detikhealth/d-0019"),
    ("Kasus Hepatitis Akut pada Anak, Ini Penjelasan Kemenkes", "https://health.detik.com/berita-detikhealth/d-0020"),
    ("Manfaat Air Putih bagi Metabolisme Tubuh Menurut Ahli", "https://health.detik.com/berita-detikhealth/d-0021"),
    ("Rutin Cek Kolesterol Penting untuk Cegah Penyakit Jantung", "https://health.detik.com/berita-detikhealth/d-0022"),
    ("Anak Sering Batuk Pilek, Kapan Harus Dibawa ke Dokter", "https://health.detik.com/berita-detikhealth/d-0023"),
    ("Pakar Sebut Stres Berkepanjangan Bisa Pengaruhi Imun Tubuh", "https://health.detik.com/berita-detikhealth/d-0024"),
    ("Kemenkes Perkuat Program Deteksi Dini Penyakit Tidak Menular", "https://health.detik.com/berita-detikhealth/d-0025"),
    ("Manfaat Meditasi untuk Kesehatan Mental dan Fisik", "https://health.detik.com/berita-detikhealth/d-0026"),
    ("Ini Alasan Pentingnya Sarapan Sehat Sebelum Beraktivitas", "https://health.detik.com/berita-detikhealth/d-0027"),
    ("Waspadai Gejala Dehidrasi saat Cuaca Panas Ekstrem", "https://health.detik.com/berita-detikhealth/d-0028"),
    ("Dokter Anak Ingatkan Bahaya Gadget Berlebihan bagi Tumbuh Kembang", "https://health.detik.com/berita-detikhealth/d-0029"),
    ("Studi Baru Ungkap Hubungan Pola Makan dengan Kesehatan Otak", "https://health.detik.com/berita-detikhealth/d-0030"),
    ("Cara Mencegah Penularan TBC di Lingkungan Rumah", "https://health.detik.com/berita-detikhealth/d-0031"),
    ("Kenali Tanda-tanda Kelelahan Kerja atau Burnout", "https://health.detik.com/berita-detikhealth/d-0032"),
    ("Manfaat Yoga untuk Fleksibilitas dan Kesehatan Tulang", "https://health.detik.com/berita-detikhealth/d-0033"),
    ("Peneliti Temukan Kaitan Kurang Gerak dengan Risiko Diabetes", "https://health.detik.com/berita-detikhealth/d-0034"),
    ("Tips Menjaga Kesehatan Mata di Era Kerja Serba Digital", "https://health.detik.com/berita-detikhealth/d-0035"),
    ("BPOM Awasi Peredaran Obat Tradisional yang Mengandung BKO", "https://health.detik.com/berita-detikhealth/d-0036"),
    ("Kenali Gejala Asam Urat dan Cara Menjaga Pola Makan", "https://health.detik.com/berita-detikhealth/d-0037"),
    ("Studi: Anak yang Cukup Tidur Miliki Konsentrasi Belajar Lebih Baik", "https://health.detik.com/berita-detikhealth/d-0038"),
    ("Pentingnya Vaksin Flu Tahunan bagi Kelompok Rentan", "https://health.detik.com/berita-detikhealth/d-0039"),
    ("Dokter Ingatkan Bahaya Merokok bagi Kesehatan Paru Jangka Panjang", "https://health.detik.com/berita-detikhealth/d-0040"),
]
